#!/usr/bin/env perl

use warnings;
use Module::Load;

use Data::Dumper;

use File::Slurp qw(read_file);

my $confdir = $ENV{"HOME"} . "/.walter/";

if (!(-d $confdir))
{
    mkdir($confdir);
}

if (!(-d $confdir . "/modules"))
{
    mkdir($confdir . "/modules");
}


if (@ARGV)
{

    unshift(@INC, $confdir . "/modules/");
    my %mappings = ();

    my @modules = split(" ", read_file($confdir . "/walter.mods"));

    
    foreach my $mod (@modules)
    {
        no warnings "redefine";
        autoload $mod;
        init(\%mappings);
    }
    
    my $verb = shift(@ARGV);
    my $handler = $mappings{$verb};
    &$handler(@ARGV);
}
