#!/usr/bin/env perl

use warnings;
use v5.10;

use CPAN;
use File::Slurp qw(read_file);
use Module::Load;


my $confdir = $ENV{"HOME"} . "/.walter/";

if (!(-d $confdir))
{
    mkdir($confdir);
}

if (!(-d $confdir . "/modules"))
{
    mkdir($confdir . "/modules");
}


if (@ARGV)
{

    unshift(@INC, $confdir . "/modules/");
    my %mappings = ();
    my @modules = split(" ", read_file($confdir . "/walter.mods"));

    
    foreach my $mod (@modules)
    {
        use Module::Installed::Tiny qw(module_installed);

        no warnings "redefine";
        autoload $mod;
        my @needs = needs();
        my @realneeds = grep { !module_installed($_) } @needs;

        if (@realneeds) {
            say "Module $mod requires the following modules: " . join(", ", @realneeds) . "\nHit enter to confirm installation, or ^C out and remove these modules from your config.";
            
            <STDIN>;
            foreach my $dep (@realneeds)
            {
                CPAN::Shell->install($dep);
            }
        }
        init(\%mappings);
    }
    
    my $verb = shift(@ARGV);

    my $handler = $mappings{$verb};
    &$handler(@ARGV);
}
