#!/usr/bin/env perl

use v5.20;
use diagnostics;

use Module::Load;

use Data::Dumper;

use File::Slurp qw(read_file);

if (@ARGV)
{

    unshift(@INC, ".");
    my %mappings = ();

    my @modules = split(" ", read_file("jarvis.mods"));

    say @modules;
    
    foreach my $mod (@modules)
    {
        say $mod;
        autoload $mod;
        init(\%mappings);
    }
    
    my $verb = shift(@ARGV);
    say("Mappings");
    my $handler = $mappings{$verb};
    &$handler(@ARGV);
}
